### ISSUE TITLE
Failed to create/update user: Plan executor error during findAndModify  email_1 dup key: { email: null }

### ISSUE THREAD

**Issue by Manmit124** [adrianhajdin/threads#39]
![Screenshot 2023-08-10 191805](https://github.com/adrianhajdin/threads/assets/112580293/f7a12255-4b90-4a24-8f67-dc29bb37915c)

please can anyone help me a little bit  give me some hint

**Comment by himeshparashar** [comment]
delete the whole database present in the mongodb and again create all sign-up 
![image](https://github.com/adrianhajdin/threads/assets/59964516/9250b93e-a687-43b0-9971-c91b2a14ce7a)


This may be due to before you have added a email in the same database and now since we are not using email field so it is becoming null

**Comment by Manmit124** [comment]
Thanks bro
