### ISSUE TITLE
Error: Failed to create/update user: Plan executor error during findAndModify :: caused by :: E11000 duplicate key error collection: test.users index: userName_1 dup key: { userName: null }

### ISSUE THREAD

**Issue by Mishael-Joe** [adrianhajdin/threads#99]
![threadserror](https://github.com/adrianhajdin/threads/assets/116783000/f7bbe912-8c5c-484c-9823-565dcbc9efe5)

**Comment by MHamza-Aslam** [comment]
can i resolve this issue

**Comment by ERy03** [comment]
I tried changing `updateUser` method from user actions and trying to find any mistakes in `AccountProfile`, but what solved my problem was **deleting the collections from mongodb.** (You can also delete the users from clerk in order to reuse your email)
In my case I had my mongoose user schema variable set as userName instead of all lowercase username. I decided to change it half way to username but because the db already had a user collection with userName, it was not allowing me to create / update. Hopefully this will help any of those who encounter this error.

<img width="291" alt="Screenshot 2024-01-12 at 21 17 50" src="https://github.com/adrianhajdin/threads/assets/76512208/e9c750af-9864-47b4-b005-bdd033cb33fb">

**Comment by Mishael-Joe** [comment]
Thanks 👍
